name: Build and deploy log-tailer
on:
  push:
    paths-ignore:
      - '*.md'

env:
  NAME: log-tailer

jobs:
  build_and_push:
    outputs:
      version: "${{ steps.build-push-sign.outputs.version }}"
    permissions:
      contents: read
      id-token: write
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # ratchet:actions/checkout@v6

      - uses: jdx/mise-action@v3
        with:
          version: 2025.12.12
          install: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: mise test

      - name: Run checks
        run: mise check

      - uses: nais/platform-build-push-sign@8be8359cd90915318ee8ab5fbc8337d04937ae70 # ratchet:nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: ${{ env.NAME }}
          google_service_account: gh-${{ env.NAME }}
          push: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
